"use client";
import { useEffect, useState, type FormEvent } from 'react';
import type { User } from '@supabase/supabase-js';
import { ArrowRight, Mail, ShieldCheck } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger } from '@/components/ui/tabs';
import { getSupabase } from '@/lib/supabase';
export default function Account({open,onOpenChange}:{open:boolean;onOpenChange:(v:boolean)=>void}){
 const [mode,setMode]=useState('signin');const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [user,setUser]=useState<User|null>(null);const [plan,setPlan]=useState('Loading…');
 const sb=getSupabase();
 useEffect(()=>{if(!sb)return;let active=true;sb.auth.getUser().then(({data})=>{if(active)setUser(data.user)});const {data}=sb.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>{active=false;data.subscription.unsubscribe()}},[sb]);
 useEffect(()=>{if(!sb||!user)return;let active=true;setPlan('Loading…');sb.from('licenses').select('plan').eq('user_id',user.id).maybeSingle().then(({data,error})=>{if(active)setPlan(error?'Unavailable':data?.plan==='premium'?'Premium':'Free')});return()=>{active=false}},[user,sb]);
 async function submit(e:FormEvent){e.preventDefault();if(!sb)return;setBusy(true);setMessage('');try{const {error}=await sb.auth.signInWithOtp({email,options:{shouldCreateUser:mode==='signup',emailRedirectTo:window.location.origin}});if(error)throw error;setMessage('Check your inbox for a secure sign-in link. You can close this window.')}catch{setMessage('We couldn’t send your link. Check your email address and try again.')}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="download-dialog account-dialog"><img src="/assets/syntra-logo.png" width="48" height="48" alt=""/><DialogTitle className="dialog-title">{user?'Your Syntra account.':'A better PC starts here.'}</DialogTitle><DialogDescription>{user?'Your account and your access, in one place.':'Sign in to manage your Syntra Optimizer account.'}</DialogDescription>{user?<><div className="account-detail"><span>Email</span><strong>{user.email}</strong><span>Your plan</span><strong>{plan}</strong></div><button className="button secondary" onClick={async()=>{const {error}=await sb!.auth.signOut();if(error)setMessage('Could not sign out. Please try again.');else setUser(null)}}>Sign out</button></>:<><Tabs value={mode} onValueChange={v=>{setMode(v);setMessage('')}}><TabsList className="account-tabs"><TabsTrigger value="signin">Sign in</TabsTrigger><TabsTrigger value="signup">Create account</TabsTrigger></TabsList></Tabs>{!sb?<div className="account-unavailable"><ShieldCheck size={23}/><h4>Accounts are coming soon.</h4><p>You’ll be able to create an account and manage your plan when Syntra launches.</p></div>:<form onSubmit={submit}><label htmlFor="account-email">Email address</label><div className="email-field"><Mail size={17}/><input id="account-email" type="email" autoComplete="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254}/></div><button className="button primary" disabled={busy}>{busy?'Sending your link…':mode==='signup'?'Create your account':'Email me a sign-in link'}<ArrowRight size={15}/></button><p className="small-note">A secure link. No password to remember.</p></form>}</>}{message&&<p role="status" className="account-message">{message}</p>}</DialogContent></Dialog>
}
