export const categories = [
  { id: 'getting-started', title: 'Getting started', description: 'Download, install and find your way around.', icon: 'download' },
  { id: 'account', title: 'Account & devices', description: 'Sign in, find your license and check your linked PC.', icon: 'user' },
  { id: 'troubleshooting', title: 'Troubleshooting', description: 'Work through download and performance issues.', icon: 'wrench' },
  { id: 'plans', title: 'Plans & payments', description: 'Understand your plan and get purchase support.', icon: 'card' },
] as const;

export const helpArticles = [
  { slug: 'install-velyro', category: 'getting-started', title: 'Install Velyro Optimizer', summary: 'Get the Windows installer and connect your account.', steps: ['Open the Download page and sign in or create a Velyro account.', 'Download the official installer for Windows 10 or Windows 11 (64-bit).', 'Open the downloaded installer and follow its instructions. If Windows or your security software flags the file, review the warning and contact support before continuing.', 'Open Velyro and sign in with the same account you use on this website.'], link: '/download', linkLabel: 'Go to downloads' },
  { slug: 'before-optimizing', category: 'getting-started', title: 'Before your first optimization', summary: 'Prepare your PC and make changes you can track.', steps: ['Save your work and back up important files before changing system settings.', 'Review each setting and its description. Start with changes you understand, rather than applying everything at once.', 'Keep a record of your original settings. If a setting offers a restore option, check how it works before applying it.', 'Compare your usual apps or games before and after each change. Performance depends on your hardware and current configuration.'], link: '/#demo', linkLabel: 'Explore the website demo' },
  { slug: 'sign-in', category: 'account', title: 'Trouble signing in?', summary: 'Check your sign-in method and recover account access.', steps: ['Use the same sign-in method you used when creating your account. A different provider may open a different account.', 'For email sign-in, check the address for typing mistakes. If you forgot your password, use the password recovery option on the sign-in page.', 'If you requested an email, check spam and junk folders. Use the most recent message.', 'If the issue continues, contact support with the error message and your sign-in method. Never send your password or a verification code.'], link: '/login', linkLabel: 'Open sign in' },
  { slug: 'linked-pc', category: 'account', title: 'Check your linked PC', summary: 'Understand device linking and hardware ID changes.', steps: ['Sign in and open your account page.', 'Find the Linked PC card to see whether a device is connected to your license.', 'Your license is tied to one PC using its hardware ID. Device information is read-only on the website.', 'If you changed hardware or need help with a different PC, contact support. There is no self-service device reset on the website.'], link: '/account', linkLabel: 'View your account' },
  { slug: 'download-issues', category: 'troubleshooting', title: 'The download does not start', summary: 'Check your session, connection and browser downloads.', steps: ['Sign in on the Download page. An account is required to access the installer.', 'Check your browser’s downloads list in case the file has already downloaded or is waiting for your attention.', 'Check your internet connection and available storage, then try the download again.', 'If your browser or security software blocks the file, keep protections enabled and contact support with the exact warning.'], link: '/download', linkLabel: 'Return to downloads' },
  { slug: 'performance', category: 'troubleshooting', title: 'Performance changed after optimizing', summary: 'Isolate the change and compare under the same conditions.', steps: ['Note which settings you changed and when the issue started.', 'Revert the most recent change using its available restore control or your recorded original value. Avoid changing several more settings at once.', 'Restart if the setting requires it, then compare the same game or application under similar conditions.', 'If the problem remains, contact support with your Windows version, Velyro version, hardware and the settings involved. No fixed FPS increase is guaranteed.'], link: '/help/before-optimizing', linkLabel: 'Read the preparation guide' },
  { slug: 'premium', category: 'plans', title: 'Find your Free or Premium plan', summary: 'Check which plan is linked to your account.', steps: ['Open your account page using the account associated with your purchase.', 'Check the displayed plan. The pricing section lists the Free and Premium options.', 'If a completed purchase is not reflected, refresh your session and check that you used the correct account.', 'Contact support with your order reference if the plan still looks incorrect. Do not purchase again to resolve an activation issue.'], link: '/account', linkLabel: 'Check your plan' },
  { slug: 'refunds', category: 'plans', title: 'Get help with a purchase or refund', summary: 'Find the policy and the details support needs.', steps: ['Read the refund policy before submitting a request.', 'Locate your order reference and purchase date.', 'Email support with those details and a description of the issue. Never include full card details, passwords or verification codes.', 'Keep your purchase receipt and support correspondence for reference.'], link: '/refund', linkLabel: 'Read the refund policy' },
] as const;
